[tool.poetry]
name = "fastapi-rest-framework"
version = "0.0.2"
description = "Restful API based on FastAPI, Pydantic and SQLAlchemy"
keywords = [
    "fastapi",
    "pydantic",
    "sqlalchemy"
]

license = "MIT"

authors = [
    "Maxim Bigin <i@flaiers.me>"
]

readme = "README.md"
homepage = "https://github.com/flaiers/fastapi-rest-framework"
repository = "https://github.com/flaiers/fastapi-rest-framework"
documentation = "https://github.com/flaiers/fastapi-rest-framework"


[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.75.0"
pydantic = "^1.9.0"
SQLAlchemy = "^1.4.32"


[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
