[tool.poetry]
name = "pyewjn"
version = "0.2.0"
description = ""
authors = ["Deepak <dmallubhotla+github@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
numpy = "^1.21.1"
scipy = "~1.8"

[tool.poetry.dev-dependencies]
pytest = ">=6"
flake8 = "^4.0.0"
pytest-cov = "^3.0.0"
mypy = "^0.942"
pytest-benchmark = "^3.4.1"
black = "^22.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--junitxml pytest.xml --cov pyewjn --cov-report=xml:coverage.xml --cov-fail-under=50 --cov-report=html"
junit_family = "xunit1"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[[tool.mypy.overrides]]
module = [
	"scipy",
	"scipy.integrate"
]
ignore_missing_imports = true
